services:
 database:
   image: mariadb:latest
   environment:
     MARIADB_ROOT_PASSWORD: "redhat"
     MARIADB_DATABASE: "wordpress"
   restart: always
   volumes:
     - db:/var/lib/mysql
 wordpress:
   image: wordpress:latest
   environment:
    WORDPRESS_DB_HOST: "database"
    WORDPRESS_DB_USER: "root"
    WORDPRESS_DB_PASSWORD: "redhat"
    WORDPRESS_DB_NAME: "wordpress"
   volumes:
    - wp:/var/www/html
   ports:
    - 80:80
volumes:
  db:
  wp: